apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: category
  name: category
  namespace: rupchand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: category
  strategy: {}
  template:
    metadata:
      labels:
        app: category
    spec:
      volumes:
      - name: log-volume
        emptyDir: {}
      containers:
      - image: rupchand1006/category:distributed
        imagePullPolicy: Always
        name: category
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: log-volume
          mountPath: "/var/tmp/"
        resources: {}
status: {}
