apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: aditya
spec:
  storageClassName: mysql-aditya
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
